name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  app:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: projet

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, pdo, sqlite
          coverage: xdebug

      - name: Install PHP dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create SQLite DB
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run Pint
        run: ./vendor/bin/pint --test

      - name: Run PHPStan
        working-directory: projet
        run: ./vendor/bin/phpstan analyse

      - name: Run Tests with coverage
        run: php artisan test --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JS dependencies
        run: npm install

      - name: Build frontend
        run: npm run build